site_name: Dwecurse Center
nav:
    - Home: index.md
    - Julia: julia.md
    - Blog: blog.md
    - About: about.md
theme:
    name: 'material'
    palette:
        primary: 'teal'
        accent: 'teal'
markdown_extensions:
  - footnotes
  - codehilite
